GMAIL_USERNAME: "ducmanhcit@gmail.com"
GMAIL_PASSWORD: "manh123456789"
FB_APP_ID: "2129257474049986"
FB_APP_SECRET: "1d2d1af6c78c2857c1fbfed4913d781b"
GG_APP_ID: "421712386455-2rakpu7vsfs3h16dgvbocdkekge0qmp2.apps.googleusercontent.com"
GG_APP_SECRET: "WwF7biIwegoBX87URFxxWvtx"
