locale: {english: en, vietnamese: vi}
validates:
  maximum_name: 50
  maximum_email: 255
  minimum_password: 6
  maximum_phone: 10
  maximum_address: 255
  maximum_name_cate: 255
  img_product_size: 3
year:
  start: 10
  end: 100
sub_email:
  num_first: 3
  num_sub: 13
sub_phone:
  num_first: 2
  num_sub: 8
product:
  paginate: 8
  admin_paginate: 8
  area:
    cols: 115
    rows: 5
cart:
  min_quantity: 1
  max_quantity: 100
  qty_add: 1
  disabled: 0
avg:
  round: 1
  value_default: 0
date_format:
  vn: "%d-%m-%Y"
comment:
  cols: 50
  rows: 4
user:
  paginate: 10
sex:
  male: 0
  female: 1
category:
  area:
    cols: 68
    rows: 7
