validates:
  maximum_name: 50
  maximum_email: 255
  minimum_password: 6
  maximum_phone: 10
  maximum_address: 255
year:
  start: 10
  end: 100
sub_email:
  num_first: 3
  num_sub: 13
sub_phone:
  num_first: 2
  num_sub: 8
product:
  paginate: 8
cart:
  min_quantity: 1
  max_quantity: 100
  qty_add: 1
